let data = [
    {model: "Hidjab",
    description:"Myagkiy",
    price: 5,
    color: "red",
    imgUrl:"Hidjab/hi.jpg"
    },
    {model: "Turban",
     description:"Modniy turban",
        price: 5,
        color: "Raznosvetniy",
        imgUrl:"turban/turban1.jpg"
    },
    {model: "Hidjab",
     description:"Brend-sharf",
        price: 5,
        color: "red",
        imgUrl:"Hidjab/hidjab2.jpg"
    },
    {model: "Chalma",
     description:"Shapka-chalma",
        price: 12,
        color: "Korichniviy",
        imgUrl:"Chalma/chalmaShapka5.jpg"
    },
    {model: "Panama",
    description:"Brend",
    price: 8,
    color: "red",
    imgUrl:"Panama/panama7.jpg"
    },
    {model: "Platok",
    description:"Shyolk",
    price: 9,
    color: "red",
    imgUrl:"Platok/platok1.jpg"
    },
    {model: "Sharf",
    description:"Dlinniy",
    price: 5,
    color: "red",
    imgUrl:"Sharfi/sharf3.jpg"
    },
    {model: "Hidjab",
    description:"Udobniy",
    price: 5,
    color: "red",
    imgUrl:"Hidjab/hidjab7.jpg"
    },
    {model: "Hidjab",
     description:"Modniy",
        price: 5,
        color: "Raznosvetniy",
        imgUrl:"Hidjab/hidjab15.jpg"
    },
    {model: "Chalma",
     description:"Shapka-chalma",
        price: 12,
        color: "Krasniy",
        imgUrl:"Chalma/calmaShapka2.jpg"
    },
    {model: "Turban",
     description:"Modniy turban",
        price: 5,
        color: "Krasniy",
        imgUrl:"turban/turban2.jpg"
    },
    {model: "Chalma",
     description:"Shapka-chalma",
        price: 17,
        color: "Zelyoniy",
        imgUrl:"Chalma/chalmaShapka3.jpg"
    },
    {model: "Turban",
     description:"Modniy turban",
        price: 5,
        color: "Siniy",
        imgUrl:"turban/turban3.jpg"
    },
    {model: "Chalma",
     description:"Shapka-chalma",
        price: 11,
        color: "Korichniviy",
        imgUrl:"Chalma/chalmaShapka9.jpg"
    },
    {model: "Turban",
     description:"Modniy turban",
        price: 5,
        color: "Rozoviy",
        imgUrl:"turban/turban4.jpg"
    },
    {model: "Chalma",
     description:"Shapka-chalma",
        price: 13,
        color: "Beliy",
        imgUrl:"Chalma/chalmaShapka5.jpg"
    },
    {model: "Turban",
     description:"Modniy turban",
        price: 5,
        color: "Siniy",
        imgUrl:"turban/turban6.jpg"
    },
    {model: "Chalma",
     description:"Shapka-chalma",
        price: 17,
        color: "Korichniviy",
        imgUrl:"Chalma/chalmaShapka6.jpg"
    },
    {model: "Turban",
     description:"Modniy turban",
        price: 5,
        color: "Siniy",
        imgUrl:"turban/turban7.jpg"
    },
    {model: "Chalma",
     description:"Shapka-chalma",
        price: 17,
        color: "Rozoviy",
        imgUrl:"Chalma/chalmaShapka7.jpg"
    },
    {model: "Turban",
     description:"Modniy turban",
        price: 5,
        color: "Raznosvetniy",
        imgUrl:"turban/turban8.jpg"
    },
    {model: "Chalma",
     description:"Shapka-chalma",
        price: 17,
        color: "Jyoltiy",
        imgUrl:"Chalma/chalmaShapka8.jpg"
    },
    {model: "Turban",
     description:"Modniy turban",
        price: 5,
        color: "Raznosvetniy",
        imgUrl:"turban/turban9.jpg"
    },
    {model: "Chalma",
     description:"Shapka-chalma",
        price: 17,
        color: "Korichniviy",
        imgUrl:"Chalma/chalmaShapka10.jpg"
    },
    {model: "Turban",
     description:"Modniy turban",
        price: 5,
        color: "Rozoviy",
        imgUrl:"turban/turban10.jpg"
    },
    {model: "Chalma",
     description:"Shapka-chalma",
        price: 17,
        color: "Rozoviy",
        imgUrl:"Chalma/chalmaShapka9.jpg"
    },
    {model: "Chalma",
     description:"Letniy chalma",
        price: 17,
        color: "Jyoltiy",
        imgUrl:"Chalma/chalma8.jpg"
    },
    {model: "Chalma",
     description:"Letniy chalma",
        price: 17,
        color: "Goluboy",
        imgUrl:"Chalma/chalma5.jpg"
    },
    {model: "Chalma",
     description:"Letniy chalma",
        price: 17,
        color: "Raznosvetniy",
        imgUrl:"Chalma/chalma6.jpg"
    },
    {model: "Chalma",
     description:"Letniy chalma",
        price: 17,
        color: "Raznosvetniy",
        imgUrl:"Chalma/chalma7.jpg"
    },
    {model: "Chalma",
     description:"Letniy chalma",
        price: 17,
        color: "Raznosvetniy",
        imgUrl:"Chalma/chalma2.jpg"
    },
    {model: "Ushanki",
     description:"Silver",
        price: 17,
        color: "Goluboy",
        imgUrl:"Ushanki/ushanki.jpg"
    },
    {model: "Chalma",
     description:"Letniy chalma",
        price: 17,
        color: "Goluboy",
        imgUrl:"Chalma/chalma1.jpg"
    },
    {model: "Chalma",
     description:"Letniy chalma",
        price: 17,
        color: "Goluboy",
        imgUrl:"Chalma/chalma.jpg"
    },
    {model: "Ushanki",
     description:"Brend",
        price: 17,
        color: "Goluboy",
        imgUrl:"Ushanki/ushanki1.jpg"
    },
    {model: "Platok",
     description:"Brend",
        price: 15,
        color: "Goluboy",
        imgUrl:"Platok/platok4.jpg"
    },
    {model: "Chalma",
     description:"Letniy chalma",
        price: 17,
        color: "Raznosvetniy",
        imgUrl:"Chalma/chalma3.jpg"
    },
    {model: "Platok",
     description:"Krasiviy",
        price: 7,
        color: "Raznosvetniy",
        imgUrl:"Platok/platok3.jpg"
    },
    {model: "Chalma",
     description:"Chalma-gold",
        price: 7,
        color: "Jyoltiy",
        imgUrl:"Chalma/chalma9.jpg"
    },
    {model: "Platok",
     description:"Golubovatiy",
        price: 11,
        color: "Goluboy",
        imgUrl:"Platok/platok2.jpg"
    },
    {model: "Chalma",
     description:"Brand",
        price: 17,
        color: "Korichniviy",
        imgUrl:"Chalma/chalma4.jpg"
    },
    {model: "Chalma",
     description:"Letniy chalma",
        price: 9,
        color: "Raznosvetniy",
        imgUrl:"Chalma/chalma10.jpg"
    },
    {model: "Chalma",
     description:"Zimniy",
        price: 23,
        color: "Rozoviy",
        imgUrl:"Chalma/calmaShapka4.jpg"
    },
    {model: "Chalma",
     description:"Zimniy",
        price: 25,
        color: "korichniviy",
        imgUrl:"Chalma/chalmaShapka1.jpg"
    },
    {model: "Turban",
     description:"Modniy turban",
        price: 14,
        color: "Siniy",
        imgUrl:"turban/turban.jpg"
    },
    {model: "Hidjab",
    description:"Raznosvetniy",
    price: 9,
    color: "Raznosvetniy",
    imgUrl:"Hidjab/hidjab1.jpg"
    },
    {model: "Hidjab",
    description:"Raduga",
    price: 12,
    color: "Raznosvetniy",
    imgUrl:"Hidjab/hidjab3.jpg"
    },
    {model: "Ushanki",
    description:"Modniy",
       price: 28,
       color: "Goluboy",
       imgUrl:"Ushanki/ushanki2.jpg"
   },
    {model: "Hidjab",
    description:"Siniy",
    price: 10,
    color: "Siniy",
    imgUrl:"Hidjab/hidjab5.jpg"
    },
    {model: "Ushanki",
    description:"Dlinniye - ushki",
       price: 31,
       color: "Koichniviy",
       imgUrl:"Ushanki/ushanki3.jpg"
   },
    {model: "Hidjab",
    description:"Dlinniy",
    price: 9,
    color: "Siniy",
    imgUrl:"Hidjab/hidjab10.jpg"
    },
    {model: "Ushanki",
    description:"Brend",
       price: 27,
       color: "Korichniviy",
       imgUrl:"Ushanki/ushanki4.jpg"
   },
    {model: "Hidjab",
    description:"Roza",
    price: 12,
    color: "Raznosvetniy",
    imgUrl:"Hidjab/hidjab6.jpg"
    },
    {model: "Ushanki",
    description:"Snow",
       price: 25,
       color: "Beliy",
       imgUrl:"Ushanki/ushanki5.jpg"
   },
    {model: "Hidjab",
    description:"Dlinniy",
    price: 14,
    color: "Goluboy",
    imgUrl:"Hidjab/hidjab8.jpg"
    },
    {model: "Hidjab",
    description:"Brand",
    price: 14,
    color: "Rozoviy",
    imgUrl:"Hidjab/hidjab11.jpg"
    },
    {model: "Hidjab",
    description:"Brand",
    price: 10,
    color: "Rozoviy",
    imgUrl:"Hidjab/hidjab18.jpg"
    },
    {model: "Hidjab",
    description:"Brand",
    price: 14,
    color: "Raznosvetniy",
    imgUrl:"Hidjab/hidjab20.jpg"
    }
    
    

    
]